#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Deploys packages/server to jbmcp.3dg.io and walks the maintainer through the
# steps only a human can do: Cloudflare login, secrets, the juicebox-web Pages
# variable, and connecting each MCP client end to end. Run from anywhere:
#   scripts/deploy-wizard.sh
# Pass/fail answers are collected and written as a markdown checklist to paste
# into the ticket.

TOTAL_STAGES=12

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER_DIR="$REPO_ROOT/packages/server"
# DEPLOY_ENV=v2 deploys the side-by-side trial Worker "juicebox-mcp-v2" on its
# *.workers.dev address (wrangler.toml [env.v2]) and leaves the prototype alone.
DEPLOY_ENV="${DEPLOY_ENV:-}"
if [[ -n "$DEPLOY_ENV" ]]; then
  WORKER_NAME="juicebox-mcp-$DEPLOY_ENV"; BASE_URL=""   # learned after deploy
else
  WORKER_NAME="juicebox-mcp"; BASE_URL="https://jbmcp.3dg.io"
fi
MCP_URL="$BASE_URL/mcp"
WS_URL="wss://${BASE_URL#https://}/ws"
# BROWSER_URL in wrangler.toml: production, or the local juicebox-web dev server for [env.v2].
if [[ -n "$DEPLOY_ENV" ]]; then PAGE_URL="http://localhost:5173/"; else PAGE_URL="https://aidenlab.org/juicebox/"; fi
RESULTS_FILE="${RESULTS_FILE:-${TMPDIR:-/tmp}/juicebox-mcp-deploy-results.md}"
RESULTS=()

wrangler() { (cd "$SERVER_DIR" && npx wrangler "$@" ${DEPLOY_ENV:+--env "$DEPLOY_ENV"}); }

# record "check" asks whether a check passed and keeps the answer for the summary.
record() {
  if confirm "$1: passed?"; then RESULTS+=("- [x] $1"); else RESULTS+=("- [ ] $1 — FAILED"); fi
}
# auto "check" STATUS keeps a result the script measured itself.
auto() {
  if [[ "$2" == ok ]]; then
    RESULTS+=("- [x] $1"); printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    RESULTS+=("- [ ] $1 — FAILED ($2)"); printf '  %s✗ %s (%s)%s\n' "$RED" "$1" "$2" "$RESET"
  fi
}
# Capture before grepping: under pipefail, grep -q exiting early can fail the pipe.
secret_is_set() { local out; out=$(wrangler secret list 2>/dev/null || true); [[ "$out" == *"\"$1\""* ]]; }

# The end-to-end run every MCP client does (ticket 17).
drive_map_load() {
  step "In a new chat, ask: \"Give me the Juicebox join link.\" (get_juicebox_url)"
  step "Open the link ($PAGE_BASE?room=…). The room widget's indicator should reach 'open'."
  step "Ask: \"Search 4DN for an HFFc6 in situ Hi-C map and load it.\" (search_maps → load_map)"
  step "Ask: \"Go to chr8:127,000,000-130,000,000.\" (goto_locus). A toast names each tool."
}

banner "juicebox-mcp: deploy and onboard"

# ──────────────────────────────────────────────────────────────────────────
stage "Before you start"
say "This deploys the Worker '$WORKER_NAME' from $SERVER_DIR"
say "to ${BASE_URL:-its *.workers.dev address}, then checks each MCP client against it."
note "Needs: npm install done at the repo root; curl; a Cloudflare account that owns"
note "the 3dg.io zone and the juicebox-web Pages project; the TinyURL account behind t.3dg.io."
printf '\n'
if [[ -n "$DEPLOY_ENV" ]]; then
  note "Side-by-side trial (DEPLOY_ENV=$DEPLOY_ENV): the prototype Worker and jbmcp.3dg.io are not touched."
else
  warn "The Worker name is the prototype's: deploying replaces the running prototype."
  warn "wrangler.toml sets workers_dev = false: the *.workers.dev URL stops answering,"
  warn "so any client still pointed there must move to $MCP_URL."
  note "To try v2 next to the prototype instead, re-run with DEPLOY_ENV=v2."
fi
confirm "Go ahead on those terms?" || { say "Stopped. Nothing changed."; exit 0; }

# ──────────────────────────────────────────────────────────────────────────
stage "Cloudflare login"
who=$(wrangler whoami 2>/dev/null || true)
if [[ "$who" == *"You are logged in"* ]]; then
  say "wrangler is already logged in:"
  printf '%s\n' "$who" | sed 's/^/    /'
  confirm "Is that the account that owns 3dg.io?" || { say "Run: (cd packages/server && npx wrangler logout), then re-run."; exit 1; }
else
  say "wrangler opens a browser tab; approve access with the account that owns 3dg.io."
  pause "Press Enter to run 'wrangler login'"
  wrangler login
  wrangler whoami | sed 's/^/    /'
  confirm "Is that the account that owns 3dg.io?" || exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Secret: SESSION_HMAC_SECRET"
say "Keys the room ids derived from ChatGPT's x-openai-session. Without it that path fails."
if secret_is_set SESSION_HMAC_SECRET; then
  note "Already set. Changing it re-maps every ChatGPT conversation to a new room."
  if confirm "Rotate it anyway?"; then
    openssl rand -hex 32 | wrangler secret put SESSION_HMAC_SECRET
  fi
else
  say "Generating 32 random bytes and storing them; nobody needs to see the value."
  openssl rand -hex 32 | wrangler secret put SESSION_HMAC_SECRET
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Secret: TINYURL_API_KEY"
say "create_shareable_url shortens snapshot links on t.3dg.io, the account juicebox-web uses"
say "(its VITE_TINYURL_JUICEBOX_API_KEY). Unset → links come back unshortened."
if secret_is_set TINYURL_API_KEY && ! confirm "Already set. Replace it?"; then
  note "Kept the existing key."
else
  open_url "https://tinyurl.com/app/dev"
  step "Sign in to the TinyURL account that owns the t.3dg.io branded domain."
  step "Create an API token (or reuse juicebox-web's) that may create TinyURLs."
  ask_secret TINYURL_API_KEY "Paste the API token (empty skips):"
  if [[ -n "$TINYURL_API_KEY" ]]; then
    printf '%s' "$TINYURL_API_KEY" | wrangler secret put TINYURL_API_KEY
  else
    SKIPPED+=("TINYURL_API_KEY (cd packages/server && npx wrangler secret put TINYURL_API_KEY)")
  fi
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Deploy the Worker"
if [[ -n "$DEPLOY_ENV" ]]; then
  say "Runs 'wrangler deploy --env $DEPLOY_ENV' in packages/server: Worker $WORKER_NAME on its"
  say "*.workers.dev address. No custom domain is touched."
  warn "If wrangler asks to move jbmcp.3dg.io to this Worker, answer N: that would take the"
  warn "domain off the prototype. (wrangler.toml's [env.$DEPLOY_ENV] sets routes = [] to prevent it.)"
else
  say "Runs 'wrangler deploy' in packages/server. The custom domain jbmcp.3dg.io is attached"
  say "by wrangler, which creates its DNS record."
  note "If it fails because jbmcp.3dg.io already has a DNS record (the prototype's), delete that"
  note "record under dash.cloudflare.com → 3dg.io → DNS → Records, then re-run this wizard."
fi
if confirm "Deploy now?"; then
  wrangler deploy
  if [[ -n "$DEPLOY_ENV" ]]; then
    ask BASE_URL "Base URL wrangler printed (https://juicebox-mcp-$DEPLOY_ENV.<account>.workers.dev)"
    BASE_URL="${BASE_URL%/}"; MCP_URL="$BASE_URL/mcp"; WS_URL="wss://${BASE_URL#https://}/ws"
  fi
else
  say "Stopped before deploying."; exit 0
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Check the deployed server"
say "Probing $MCP_URL (a new custom domain can take a minute to get its certificate)."
hdrs=$(curl -s -o /dev/null -D - --max-time 15 -X POST "$MCP_URL" \
  -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \
  -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"deploy-wizard","version":"0"}}}' || true)
room=$(printf '%s' "$hdrs" | tr -d '\r' | awk -F': ' 'tolower($1)=="mcp-session-id"{print $2}')
if [[ "$room" =~ ^[0-9A-HJKMNP-TV-Z]{10}$ ]]; then
  auto "/mcp initialize answers on ${BASE_URL#https://} with a room id ($room)" ok
else
  auto "/mcp initialize answers on ${BASE_URL#https://} with a room id" "$(printf '%s' "$hdrs" | head -n1 | tr -d '\r')"
fi
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$MCP_URL" || true)
[[ "$code" == 405 ]] && auto "GET /mcp is refused (405)" ok || auto "GET /mcp is refused (405)" "got $code"
ws() { curl -s -o /dev/null -w '%{http_code}' --http1.1 --max-time 5 \
  -H 'Connection: Upgrade' -H 'Upgrade: websocket' -H 'Sec-WebSocket-Version: 13' \
  -H 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' -H "Origin: $1" "$BASE_URL/ws" || true; }
code=$(ws https://example.com)
[[ "$code" == 403 ]] && auto "/ws refuses an unlisted Origin (403)" ok || auto "/ws refuses an unlisted Origin (403)" "got $code"
code=$(ws https://aidenlab.org)
[[ "$code" == 101* ]] && auto "/ws accepts https://aidenlab.org (101)" ok || auto "/ws accepts https://aidenlab.org (101)" "got $code"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "juicebox-web: VITE_WS_URL on Cloudflare Pages"
say "juicebox-web renders the room widget only when built with VITE_WS_URL."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Workers & Pages → juicebox-web → Settings → Variables and Secrets."
step "Production: add a plain-text variable VITE_WS_URL = $WS_URL"
step "Preview: add the same variable with the same value."
step "Deployments → latest production deployment → ⋯ → Retry deployment (vars apply at build)."
note "Preview builds are served from <hash>.juicebox-web.pages.dev, which is not on"
note "ALLOWED_ORIGINS (exact match): the widget renders there but /ws answers 403."
note "The widget ships once juicebox-web's ticket 16 PR lands on the branch Pages builds."
record "Pages env has VITE_WS_URL for production and preview"

# ──────────────────────────────────────────────────────────────────────────
stage "A page to drive"
if [[ -n "$DEPLOY_ENV" ]]; then
  say "Join links from $WORKER_NAME open $PAGE_URL (BROWSER_URL in [env.$DEPLOY_ENV]);"
  say "nothing is deployed to the production site. Run a local juicebox-web with the widget:"
  step "cd ../juicebox-web-16 (the fork worktree on branch ticket/16)"
  step "VITE_WS_URL=$WS_URL npm run dev   # vite on http://localhost:5173"
  PAGE_BASE="$PAGE_URL"
  pause "Press Enter once http://localhost:5173/ loads and shows the room item next to Share"
elif open_url "$PAGE_URL"; say "Join links open $PAGE_URL. Is the room widget live there yet?"; \
     step "Look for the room item next to Share in the navbar."; confirm "Is the widget there?"; then
  PAGE_BASE="$PAGE_URL"
else
  say "Then drive a local juicebox-web against the deployed server instead:"
  step "cd ../juicebox-web (a checkout with the widget, e.g. branch ticket/16)"
  step "VITE_WS_URL=$WS_URL npm run dev   # vite on http://localhost:5173"
  note "http://localhost:5173 is on ALLOWED_ORIGINS. In each join link below, replace"
  note "$PAGE_URL with http://localhost:5173/ and keep ?room=…"
  PAGE_BASE="http://localhost:5173/"
  pause "Press Enter once http://localhost:5173/ loads"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Claude Desktop: custom connector"
step "Claude Desktop → Settings → Connectors → Add custom connector."
step "Name: Juicebox   ·   Remote MCP server URL: $MCP_URL   → Add."
step "In a new chat, check Juicebox is enabled in the chat's tools menu."
drive_map_load
record "Claude Desktop custom connector: get_juicebox_url → open page → load_map → goto_locus"

# ──────────────────────────────────────────────────────────────────────────
stage "Claude Code"
step "In a terminal:  claude mcp add --transport http juicebox $MCP_URL"
step "Start 'claude', run /mcp, and check 'juicebox' is connected."
drive_map_load
record "Claude Code (--transport http): get_juicebox_url → open page → load_map → goto_locus"

# ──────────────────────────────────────────────────────────────────────────
stage "mcp-remote (stdio bridge)"
say "For clients without remote-connector support. Turn the custom connector off first,"
say "so the tools are not listed twice. In claude_desktop_config.json"
note "(Settings → Developer → Edit Config), add under \"mcpServers\":"
cat <<JSON
      "juicebox-remote": {
        "command": "npx",
        "args": ["-y", "mcp-remote", "$MCP_URL"]
      }
JSON
step "Quit and reopen Claude Desktop; 'juicebox-remote' should appear in the chat's tools menu."
drive_map_load
record "mcp-remote: get_juicebox_url → open page → load_map → goto_locus"

# ──────────────────────────────────────────────────────────────────────────
stage "Two pages, one room (design §10 step 4)"
say "On $PAGE_BASE, with the room from the last stage still open in tab A:"
step "Copy the join link from the widget, open it in tab B; B should show A's map."
step "In A, change the locus, normalization, colour scale and add a track; B follows."
record "Two tabs on one room stay in sync"
step "Close both tabs, then open the join link again in a fresh tab C."
record "A late joiner receives the room's saved session"
step "In A (or C): Share → copy the snapshot link; open it in a private window."
record "The snapshot link restores the view"

finish
{
  printf '**%s — deploy wizard (scripts/deploy-wizard.sh).**\n\n' "$(date +%F)"
  printf '%s\n' "${RESULTS[@]}"
  (( ${#SKIPPED[@]} )) && printf '\nStill to do: %s\n' "${SKIPPED[*]}"
} > "$RESULTS_FILE"
say "Results, ready to paste into .scratch/v2/issues/17-*.md under Comments:"
note "$RESULTS_FILE"
printf '\n'; sed 's/^/    /' "$RESULTS_FILE"; printf '\n'
